version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=elastest
      - POSTGRES_PASSWORD=elastestpassword
      - POSTGRES_DB=ece
  ece:
    image: elastest/ece:0.5.0
    ports:
      - 8888:8888
    environment:
      - ELASTESTTORMAPI=http://localhost:37006
      - ELASTESTESMAPI=http://localhost:37005
      - ELASTESTTORMTJOBENDPOINT=/api/tjob
      - ELASTESTESMCATALOGENDPOINT=/v2/catalog
      - ELASTESTESMINSTANCEENDPOINT=/v2/et/service_instances/