version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=elastest
      - POSTGRES_PASSWORD=elastestpassword
      - POSTGRES_DB=ece
  ece:
    image: elastest/ece
    ports:
      - 8888:8888
